version: '3.9'
services:
  client:
    networks:
      - traefik
    build:
      context: ./
      dockerfile: Dockerfile
    labels:
      traefik.enable: true
      traefik.http.routers.client.rule: Host(`boket78.com`) || Host(`www.boket78.com`)
      traefik.http.routers.client.entrypoints: https

networks:
    traefik:
        external: true