version: '3.9'
services:
  proxy:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
     - 82:80
    depends_on:
     - client
  client:
    build:
      context: ./
      dockerfile: Dockerfile
